# Generated by Django 5.1.4 on 2025-01-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitors_details',
            new_name='VisitorsDetails',
        ),
    ]
